name: Feature Request
description: Suggest an idea for this project
title: "[Feature request] "
labels: ["feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched for existing issues (open and closed) and confirmed this feature hasn't been requested before
          required: true
        - label: I believe this feature request will benefit more than 10% of users, not just myself
          required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Please provide a clear and detailed description of the feature you'd like to see added
      placeholder: Describe your feature request here...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the problem this feature would solve or the use case it would enable
      placeholder: What problem does this solve? How would you use this feature?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
